require("user.colorscheme.themes.catppuccin")
require("user.colorscheme.themes.nightfox")
require("user.colorscheme.themes.onedark")
require("user.colorscheme.themes.kanagawa")
require("user.colorscheme.themes.tokyonight")
