#! /bin/sh

#
# bspwm settings
#

CONF_DIR="$HOME/.config/bspwm"

# Set screens resolutions
SCREEN_0_SIZE="1920x1080"
xrandr --output eDP-1 --mode $SCREEN_0_SIZE;

# Initiate desktops
$CONF_DIR/bspwm-ws.sh --init

bspc config border_width			3
bspc config normal_border_color		"#303446"
bspc config focused_border_color	"#babbf1"
bspc config window_gap				12

bspc config split_ratio				0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			false
bspc config single_monocle			true

bspc config click_to_focus			true
bspc config pointer_follows_monitor	true
bspc config focus_follows_pointer	false

# bspc config presel_feedback			false

# bspwm rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
# bspc rule -a Code desktop='^3'
# bspc rule -a Spotify desktop='^5'
# bspc rule -a Lutris desktop='^6'

bspc rule -a Arandr:*:* state=floating rectangle=720x540+600+270
bspc rule -a Nemo state=floating
bspc rule -a Thunar state=floating
bspc rule -a File-roller state=floating
bspc rule -a Seahorse state=floating
bspc rule -a Virt-manager state=floating
bspc rule -a "VirtualBox Manager" state=floating
bspc rule -a Gnome-control-center state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Baobab state=floating
bspc rule -a Cinnamon-settings.py state=floating
bspc rule -a "cinnamon-settings network" state=floating
bspc rule -a "MintSources.py" state=floating
bspc rule -a Xfce4-settings-manager state=floating
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Gnome-tweaks state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a "Webapp-manager.py" state= floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Protonvpn state=floating
bspc rule -a Protonvpn-app state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Gnome-font-viewer state=floating
bspc rule -a Gnome-calendar state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Gnome-terminal state=floating
bspc rule -a Grub-customizer state=floating
bspc rule -a Cheese state=floating
bspc rule -a Zathura state=tiled
bspc rule -a AppFlowy state=tiled
bspc rule -a kdeconnect.app state=floating
bspc rule -a Tlmgr state=floating
bspc rule -a miktex-console state=floating
bspc rule -a zoom state=floating
bspc rule -a "*:vn.hoabinh.quan.CoBang:*" state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Nmtui state=floating

bspc config external_rules_command $CONF_DIR/external_rules

# Java apps
export _JAVA_AWT_WM_NONREPARENTING=1


#
# Start up apps
#
# Polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
# /usr/libexec/polkit-gnome-authentication-agent-1 &
# lxpolkit &
gnome-keyring-daemon -r -d
/usr/bin/gnome-keyring-daemon --start --daemonize --components ssh,secrets,pkcs11 &
# eval $(ssh-agent -s)

# picom --legacy-backends &
picom &
# --transparent-clipping --experimental-backends &
$CONF_DIR/cleanfullscreen &

# Start input method for Vietnamese typing
ibus-daemon -rd &
ibus engine Bamboo;
ibus restart;

# Power manager
# xfce4-power-manager &

# Network Manager tray icon
nm-applet &

# bspwm-specific start up apps
sxhkd -c $CONF_DIR/sxhkdrc &
feh --bg-scale $HOME/OSsetup/Backgrounds/Wallpapers/pistachio-parazeeknova-wall.png &
$HOME/.config/polybar/launch.sh --catppuccin &

# Screenlight
# pgrep -x fluxgui >/dev/null && : || fluxgui &
# pkill redshift && pgrep -x redshift >/dev/null && : || redshift-gtk &

#
# Lockscreen
#
# xset dpms 600 &
# xss-lock -- i3lock -n -i $HOME/OSsetup/Backgrounds/Lockscreens/lockscreen_1.png &
xautolock -time 10 -corners ---- -locker "i3lock -t -i $HOME/OSsetup/Backgrounds/Lockscreens/lockscreen_6_$SCREEN_0_SIZE.png; ibus restart" -detectsleep -killtime 10 -killer "systemctl suspend" &
# Keep the screen unlocked in full screen mode
caffeine &

#
# Cursor
#
xsetroot -cursor_name left_ptr

#
# Detecting monitor change
#
#
# Create a service file under ~/.config/systemd/user named bspwm-reload.service
#
# [Unit]
# Description=Reload BSPWM
#
# [Service]
# Type=oneshot
# ExecStart=/bin/bash -c "bspc wm -r"
# StandardOutput=journal
#
# Create a udev rule to trigger the service above, create the file named 99-reload-monitor.rules under /etc/udev/rules.d
#
# ACTION=="change", SUBSYSTEM=="drm", RUN+="/bin/su nhattan --command=systemctl --user start bspwm-reload.service''"


